/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OrganizationGraphicsResponse,
  OrganizationMetricsResponse,
  OrganizationSettingsResponse,
} from '../models/index';
import {
    OrganizationGraphicsResponseFromJSON,
    OrganizationGraphicsResponseToJSON,
    OrganizationMetricsResponseFromJSON,
    OrganizationMetricsResponseToJSON,
    OrganizationSettingsResponseFromJSON,
    OrganizationSettingsResponseToJSON,
} from '../models/index';

export interface GetOrganizationGraphicsRequest {
    organizationId: string;
}

export interface GetOrganizationMetricsRequest {
    organizationId: string;
}

export interface GetOrganizationSettingsRequest {
    organizationId: string;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Get organization graphics
     */
    async getOrganizationGraphicsRaw(requestParameters: GetOrganizationGraphicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationGraphicsResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getOrganizationGraphics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{organizationId}/graphics`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationGraphicsResponseFromJSON(jsonValue));
    }

    /**
     * Get organization graphics
     */
    async getOrganizationGraphics(requestParameters: GetOrganizationGraphicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationGraphicsResponse> {
        const response = await this.getOrganizationGraphicsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get organization metrics
     */
    async getOrganizationMetricsRaw(requestParameters: GetOrganizationMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationMetricsResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getOrganizationMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{organizationId}/metrics`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationMetricsResponseFromJSON(jsonValue));
    }

    /**
     * Get organization metrics
     */
    async getOrganizationMetrics(requestParameters: GetOrganizationMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationMetricsResponse> {
        const response = await this.getOrganizationMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get organization settings
     */
    async getOrganizationSettingsRaw(requestParameters: GetOrganizationSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationSettingsResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getOrganizationSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{organizationId}/settings`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationSettingsResponseFromJSON(jsonValue));
    }

    /**
     * Get organization settings
     */
    async getOrganizationSettings(requestParameters: GetOrganizationSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationSettingsResponse> {
        const response = await this.getOrganizationSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
