/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QueueGraphicsResponse,
  QueueMembersResponse,
  QueueMetricsResponse,
  QueueSettingsResponse,
} from '../models/index';
import {
    QueueGraphicsResponseFromJSON,
    QueueGraphicsResponseToJSON,
    QueueMembersResponseFromJSON,
    QueueMembersResponseToJSON,
    QueueMetricsResponseFromJSON,
    QueueMetricsResponseToJSON,
    QueueSettingsResponseFromJSON,
    QueueSettingsResponseToJSON,
} from '../models/index';

export interface GetQueueGraphicsRequest {
    queueId: string;
}

export interface GetQueueMembersRequest {
    queueId: string;
}

export interface GetQueueMetricsRequest {
    queueId: string;
}

export interface GetQueueSettingsRequest {
    queueId: string;
}

/**
 * 
 */
export class QueuesApi extends runtime.BaseAPI {

    /**
     * Get queue graphics
     */
    async getQueueGraphicsRaw(requestParameters: GetQueueGraphicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueGraphicsResponse>> {
        if (requestParameters['queueId'] == null) {
            throw new runtime.RequiredError(
                'queueId',
                'Required parameter "queueId" was null or undefined when calling getQueueGraphics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/queues/{queueId}/graphics`;
        urlPath = urlPath.replace(`{${"queueId"}}`, encodeURIComponent(String(requestParameters['queueId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueGraphicsResponseFromJSON(jsonValue));
    }

    /**
     * Get queue graphics
     */
    async getQueueGraphics(requestParameters: GetQueueGraphicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueGraphicsResponse> {
        const response = await this.getQueueGraphicsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get members of a queue
     */
    async getQueueMembersRaw(requestParameters: GetQueueMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueMembersResponse>> {
        if (requestParameters['queueId'] == null) {
            throw new runtime.RequiredError(
                'queueId',
                'Required parameter "queueId" was null or undefined when calling getQueueMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/queues/{queueId}/members`;
        urlPath = urlPath.replace(`{${"queueId"}}`, encodeURIComponent(String(requestParameters['queueId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueMembersResponseFromJSON(jsonValue));
    }

    /**
     * Get members of a queue
     */
    async getQueueMembers(requestParameters: GetQueueMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueMembersResponse> {
        const response = await this.getQueueMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get queue metrics
     */
    async getQueueMetricsRaw(requestParameters: GetQueueMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueMetricsResponse>> {
        if (requestParameters['queueId'] == null) {
            throw new runtime.RequiredError(
                'queueId',
                'Required parameter "queueId" was null or undefined when calling getQueueMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/queues/{queueId}/metrics`;
        urlPath = urlPath.replace(`{${"queueId"}}`, encodeURIComponent(String(requestParameters['queueId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueMetricsResponseFromJSON(jsonValue));
    }

    /**
     * Get queue metrics
     */
    async getQueueMetrics(requestParameters: GetQueueMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueMetricsResponse> {
        const response = await this.getQueueMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get queue settings
     */
    async getQueueSettingsRaw(requestParameters: GetQueueSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueSettingsResponse>> {
        if (requestParameters['queueId'] == null) {
            throw new runtime.RequiredError(
                'queueId',
                'Required parameter "queueId" was null or undefined when calling getQueueSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/queues/{queueId}/settings`;
        urlPath = urlPath.replace(`{${"queueId"}}`, encodeURIComponent(String(requestParameters['queueId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueSettingsResponseFromJSON(jsonValue));
    }

    /**
     * Get queue settings
     */
    async getQueueSettings(requestParameters: GetQueueSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueSettingsResponse> {
        const response = await this.getQueueSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
