/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QueueEntryCreatingRequest,
  QueueEntryResponse,
} from '../models/index';
import {
    QueueEntryCreatingRequestFromJSON,
    QueueEntryCreatingRequestToJSON,
    QueueEntryResponseFromJSON,
    QueueEntryResponseToJSON,
} from '../models/index';

export interface AddQueueEntryRequest {
    queueEntryCreatingRequest?: QueueEntryCreatingRequest;
}

export interface DeleteQueueEntryRequest {
    entryId: string;
}

export interface GetQueueEntryRequest {
    entryId: string;
}

/**
 * 
 */
export class QueueEntriesApi extends runtime.BaseAPI {

    /**
     * Add user in queue
     */
    async addQueueEntryRaw(requestParameters: AddQueueEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/queue-entries`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueueEntryCreatingRequestToJSON(requestParameters['queueEntryCreatingRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add user in queue
     */
    async addQueueEntry(requestParameters: AddQueueEntryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addQueueEntryRaw(requestParameters, initOverrides);
    }

    /**
     * Delete user from queue
     */
    async deleteQueueEntryRaw(requestParameters: DeleteQueueEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['entryId'] == null) {
            throw new runtime.RequiredError(
                'entryId',
                'Required parameter "entryId" was null or undefined when calling deleteQueueEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/queue-entries/{entryId}`;
        urlPath = urlPath.replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters['entryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete user from queue
     */
    async deleteQueueEntry(requestParameters: DeleteQueueEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteQueueEntryRaw(requestParameters, initOverrides);
    }

    /**
     * Get queue entry
     */
    async getQueueEntryRaw(requestParameters: GetQueueEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueEntryResponse>> {
        if (requestParameters['entryId'] == null) {
            throw new runtime.RequiredError(
                'entryId',
                'Required parameter "entryId" was null or undefined when calling getQueueEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/queue-entries/{entryId}`;
        urlPath = urlPath.replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters['entryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueEntryResponseFromJSON(jsonValue));
    }

    /**
     * Get queue entry
     */
    async getQueueEntry(requestParameters: GetQueueEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueEntryResponse> {
        const response = await this.getQueueEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
