/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OrganizationQueuesResponse,
  SendUserMiniAppDataRequest,
  UserCreatingRequest,
  UserResponse,
  UserRoleRequest,
  UserUpdateRequest,
} from '../models/index';
import {
    OrganizationQueuesResponseFromJSON,
    OrganizationQueuesResponseToJSON,
    SendUserMiniAppDataRequestFromJSON,
    SendUserMiniAppDataRequestToJSON,
    UserCreatingRequestFromJSON,
    UserCreatingRequestToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
    UserRoleRequestFromJSON,
    UserRoleRequestToJSON,
    UserUpdateRequestFromJSON,
    UserUpdateRequestToJSON,
} from '../models/index';

export interface AddUserInMaxQueueSystemRequest {
    userCreatingRequest?: UserCreatingRequest;
}

export interface GetUserByMaxIdRequest {
    maxId: number;
}

export interface SendUserMiniAppDataOperationRequest {
    maxId: number;
    sendUserMiniAppDataRequest?: SendUserMiniAppDataRequest;
}

export interface UpdateOrganizationUserRoleRequest {
    maxId: number;
    userRoleRequest?: UserRoleRequest;
}

export interface UpdateUserInMaxQueueSystemRequest {
    maxId: number;
    userUpdateRequest?: UserUpdateRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Add user in maxqueue system
     */
    async addUserInMaxQueueSystemRaw(requestParameters: AddUserInMaxQueueSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreatingRequestToJSON(requestParameters['userCreatingRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add user in maxqueue system
     */
    async addUserInMaxQueueSystem(requestParameters: AddUserInMaxQueueSystemRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addUserInMaxQueueSystemRaw(requestParameters, initOverrides);
    }

    /**
     * Get user by Max Messenger ID
     */
    async getUserByMaxIdRaw(requestParameters: GetUserByMaxIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['maxId'] == null) {
            throw new runtime.RequiredError(
                'maxId',
                'Required parameter "maxId" was null or undefined when calling getUserByMaxId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{maxId}`;
        urlPath = urlPath.replace(`{${"maxId"}}`, encodeURIComponent(String(requestParameters['maxId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Get user by Max Messenger ID
     */
    async getUserByMaxId(requestParameters: GetUserByMaxIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.getUserByMaxIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Transfer data after opening the mini-app
     */
    async sendUserMiniAppDataRaw(requestParameters: SendUserMiniAppDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['maxId'] == null) {
            throw new runtime.RequiredError(
                'maxId',
                'Required parameter "maxId" was null or undefined when calling sendUserMiniAppData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{maxId}/mini-app`;
        urlPath = urlPath.replace(`{${"maxId"}}`, encodeURIComponent(String(requestParameters['maxId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendUserMiniAppDataRequestToJSON(requestParameters['sendUserMiniAppDataRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Transfer data after opening the mini-app
     */
    async sendUserMiniAppData(requestParameters: SendUserMiniAppDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendUserMiniAppDataRaw(requestParameters, initOverrides);
    }

    /**
     * Update user role in organization
     */
    async updateOrganizationUserRoleRaw(requestParameters: UpdateOrganizationUserRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationQueuesResponse>> {
        if (requestParameters['maxId'] == null) {
            throw new runtime.RequiredError(
                'maxId',
                'Required parameter "maxId" was null or undefined when calling updateOrganizationUserRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{maxId}/role`;
        urlPath = urlPath.replace(`{${"maxId"}}`, encodeURIComponent(String(requestParameters['maxId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserRoleRequestToJSON(requestParameters['userRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationQueuesResponseFromJSON(jsonValue));
    }

    /**
     * Update user role in organization
     */
    async updateOrganizationUserRole(requestParameters: UpdateOrganizationUserRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationQueuesResponse> {
        const response = await this.updateOrganizationUserRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update user in maxqueue system
     */
    async updateUserInMaxQueueSystemRaw(requestParameters: UpdateUserInMaxQueueSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['maxId'] == null) {
            throw new runtime.RequiredError(
                'maxId',
                'Required parameter "maxId" was null or undefined when calling updateUserInMaxQueueSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{maxId}`;
        urlPath = urlPath.replace(`{${"maxId"}}`, encodeURIComponent(String(requestParameters['maxId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateRequestToJSON(requestParameters['userUpdateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update user in maxqueue system
     */
    async updateUserInMaxQueueSystem(requestParameters: UpdateUserInMaxQueueSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateUserInMaxQueueSystemRaw(requestParameters, initOverrides);
    }

}
