/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationSettings } from './OrganizationSettings';
import {
    OrganizationSettingsFromJSON,
    OrganizationSettingsFromJSONTyped,
    OrganizationSettingsToJSON,
    OrganizationSettingsToJSONTyped,
} from './OrganizationSettings';

/**
 * 
 * @export
 * @interface OrganizationSettingsResponse
 */
export interface OrganizationSettingsResponse {
    /**
     * 
     * @type {OrganizationSettings}
     * @memberof OrganizationSettingsResponse
     */
    organization?: OrganizationSettings;
}

/**
 * Check if a given object implements the OrganizationSettingsResponse interface.
 */
export function instanceOfOrganizationSettingsResponse(value: object): value is OrganizationSettingsResponse {
    return true;
}

export function OrganizationSettingsResponseFromJSON(json: any): OrganizationSettingsResponse {
    return OrganizationSettingsResponseFromJSONTyped(json, false);
}

export function OrganizationSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : OrganizationSettingsFromJSON(json['organization']),
    };
}

export function OrganizationSettingsResponseToJSON(json: any): OrganizationSettingsResponse {
    return OrganizationSettingsResponseToJSONTyped(json, false);
}

export function OrganizationSettingsResponseToJSONTyped(value?: OrganizationSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': OrganizationSettingsToJSON(value['organization']),
    };
}

