/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationMetrics
 */
export interface OrganizationMetrics {
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    numberOfActiveQueues?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    numberOfQueues?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    numberOfMembersInAllQueues?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    numberOfEmployees?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    membersInDay?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    waitingTime?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    averageLoadInQueues?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationMetrics
     */
    numberOfServedMembers?: number;
}

/**
 * Check if a given object implements the OrganizationMetrics interface.
 */
export function instanceOfOrganizationMetrics(value: object): value is OrganizationMetrics {
    return true;
}

export function OrganizationMetricsFromJSON(json: any): OrganizationMetrics {
    return OrganizationMetricsFromJSONTyped(json, false);
}

export function OrganizationMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfActiveQueues': json['numberOfActiveQueues'] == null ? undefined : json['numberOfActiveQueues'],
        'numberOfQueues': json['numberOfQueues'] == null ? undefined : json['numberOfQueues'],
        'numberOfMembersInAllQueues': json['numberOfMembersInAllQueues'] == null ? undefined : json['numberOfMembersInAllQueues'],
        'numberOfEmployees': json['numberOfEmployees'] == null ? undefined : json['numberOfEmployees'],
        'membersInDay': json['membersInDay'] == null ? undefined : json['membersInDay'],
        'waitingTime': json['waitingTime'] == null ? undefined : json['waitingTime'],
        'averageLoadInQueues': json['averageLoadInQueues'] == null ? undefined : json['averageLoadInQueues'],
        'numberOfServedMembers': json['numberOfServedMembers'] == null ? undefined : json['numberOfServedMembers'],
    };
}

export function OrganizationMetricsToJSON(json: any): OrganizationMetrics {
    return OrganizationMetricsToJSONTyped(json, false);
}

export function OrganizationMetricsToJSONTyped(value?: OrganizationMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfActiveQueues': value['numberOfActiveQueues'],
        'numberOfQueues': value['numberOfQueues'],
        'numberOfMembersInAllQueues': value['numberOfMembersInAllQueues'],
        'numberOfEmployees': value['numberOfEmployees'],
        'membersInDay': value['membersInDay'],
        'waitingTime': value['waitingTime'],
        'averageLoadInQueues': value['averageLoadInQueues'],
        'numberOfServedMembers': value['numberOfServedMembers'],
    };
}

