/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationGraphicsTotalLoadByTimeInner
 */
export interface OrganizationGraphicsTotalLoadByTimeInner {
    /**
     * 
     * @type {Date}
     * @memberof OrganizationGraphicsTotalLoadByTimeInner
     */
    time?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrganizationGraphicsTotalLoadByTimeInner
     */
    totalLoad?: number;
}

/**
 * Check if a given object implements the OrganizationGraphicsTotalLoadByTimeInner interface.
 */
export function instanceOfOrganizationGraphicsTotalLoadByTimeInner(value: object): value is OrganizationGraphicsTotalLoadByTimeInner {
    return true;
}

export function OrganizationGraphicsTotalLoadByTimeInnerFromJSON(json: any): OrganizationGraphicsTotalLoadByTimeInner {
    return OrganizationGraphicsTotalLoadByTimeInnerFromJSONTyped(json, false);
}

export function OrganizationGraphicsTotalLoadByTimeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGraphicsTotalLoadByTimeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'totalLoad': json['totalLoad'] == null ? undefined : json['totalLoad'],
    };
}

export function OrganizationGraphicsTotalLoadByTimeInnerToJSON(json: any): OrganizationGraphicsTotalLoadByTimeInner {
    return OrganizationGraphicsTotalLoadByTimeInnerToJSONTyped(json, false);
}

export function OrganizationGraphicsTotalLoadByTimeInnerToJSONTyped(value?: OrganizationGraphicsTotalLoadByTimeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
        'totalLoad': value['totalLoad'],
    };
}

