/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationSettings
 */
export interface OrganizationSettings {
    /**
     * 
     * @type {string}
     * @memberof OrganizationSettings
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSettings
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSettings
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSettings
     */
    address?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationSettings
     */
    isBanned?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationSettings
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the OrganizationSettings interface.
 */
export function instanceOfOrganizationSettings(value: object): value is OrganizationSettings {
    return true;
}

export function OrganizationSettingsFromJSON(json: any): OrganizationSettings {
    return OrganizationSettingsFromJSONTyped(json, false);
}

export function OrganizationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'address': json['address'] == null ? undefined : json['address'],
        'isBanned': json['isBanned'] == null ? undefined : json['isBanned'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function OrganizationSettingsToJSON(json: any): OrganizationSettings {
    return OrganizationSettingsToJSONTyped(json, false);
}

export function OrganizationSettingsToJSONTyped(value?: OrganizationSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'address': value['address'],
        'isBanned': value['isBanned'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

