/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationMetrics } from './OrganizationMetrics';
import {
    OrganizationMetricsFromJSON,
    OrganizationMetricsFromJSONTyped,
    OrganizationMetricsToJSON,
    OrganizationMetricsToJSONTyped,
} from './OrganizationMetrics';

/**
 * 
 * @export
 * @interface OrganizationMetricsResponse
 */
export interface OrganizationMetricsResponse {
    /**
     * 
     * @type {OrganizationMetrics}
     * @memberof OrganizationMetricsResponse
     */
    metrics?: OrganizationMetrics;
}

/**
 * Check if a given object implements the OrganizationMetricsResponse interface.
 */
export function instanceOfOrganizationMetricsResponse(value: object): value is OrganizationMetricsResponse {
    return true;
}

export function OrganizationMetricsResponseFromJSON(json: any): OrganizationMetricsResponse {
    return OrganizationMetricsResponseFromJSONTyped(json, false);
}

export function OrganizationMetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationMetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metrics': json['metrics'] == null ? undefined : OrganizationMetricsFromJSON(json['metrics']),
    };
}

export function OrganizationMetricsResponseToJSON(json: any): OrganizationMetricsResponse {
    return OrganizationMetricsResponseToJSONTyped(json, false);
}

export function OrganizationMetricsResponseToJSONTyped(value?: OrganizationMetricsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metrics': OrganizationMetricsToJSON(value['metrics']),
    };
}

