/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleQueue } from './SimpleQueue';
import {
    SimpleQueueFromJSON,
    SimpleQueueFromJSONTyped,
    SimpleQueueToJSON,
    SimpleQueueToJSONTyped,
} from './SimpleQueue';

/**
 * 
 * @export
 * @interface OrganizationQueuesResponse
 */
export interface OrganizationQueuesResponse {
    /**
     * 
     * @type {Array<SimpleQueue>}
     * @memberof OrganizationQueuesResponse
     */
    queues?: Array<SimpleQueue>;
}

/**
 * Check if a given object implements the OrganizationQueuesResponse interface.
 */
export function instanceOfOrganizationQueuesResponse(value: object): value is OrganizationQueuesResponse {
    return true;
}

export function OrganizationQueuesResponseFromJSON(json: any): OrganizationQueuesResponse {
    return OrganizationQueuesResponseFromJSONTyped(json, false);
}

export function OrganizationQueuesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationQueuesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'queues': json['queues'] == null ? undefined : ((json['queues'] as Array<any>).map(SimpleQueueFromJSON)),
    };
}

export function OrganizationQueuesResponseToJSON(json: any): OrganizationQueuesResponse {
    return OrganizationQueuesResponseToJSONTyped(json, false);
}

export function OrganizationQueuesResponseToJSONTyped(value?: OrganizationQueuesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queues': value['queues'] == null ? undefined : ((value['queues'] as Array<any>).map(SimpleQueueToJSON)),
    };
}

