/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationGraphicsThroughputByTimeInner } from './OrganizationGraphicsThroughputByTimeInner';
import {
    OrganizationGraphicsThroughputByTimeInnerFromJSON,
    OrganizationGraphicsThroughputByTimeInnerFromJSONTyped,
    OrganizationGraphicsThroughputByTimeInnerToJSON,
    OrganizationGraphicsThroughputByTimeInnerToJSONTyped,
} from './OrganizationGraphicsThroughputByTimeInner';
import type { OrganizationGraphicsTotalLoadByTimeInner } from './OrganizationGraphicsTotalLoadByTimeInner';
import {
    OrganizationGraphicsTotalLoadByTimeInnerFromJSON,
    OrganizationGraphicsTotalLoadByTimeInnerFromJSONTyped,
    OrganizationGraphicsTotalLoadByTimeInnerToJSON,
    OrganizationGraphicsTotalLoadByTimeInnerToJSONTyped,
} from './OrganizationGraphicsTotalLoadByTimeInner';

/**
 * 
 * @export
 * @interface OrganizationGraphics
 */
export interface OrganizationGraphics {
    /**
     * 
     * @type {Array<OrganizationGraphicsThroughputByTimeInner>}
     * @memberof OrganizationGraphics
     */
    throughputByTime?: Array<OrganizationGraphicsThroughputByTimeInner>;
    /**
     * 
     * @type {Array<OrganizationGraphicsTotalLoadByTimeInner>}
     * @memberof OrganizationGraphics
     */
    totalLoadByTime?: Array<OrganizationGraphicsTotalLoadByTimeInner>;
}

/**
 * Check if a given object implements the OrganizationGraphics interface.
 */
export function instanceOfOrganizationGraphics(value: object): value is OrganizationGraphics {
    return true;
}

export function OrganizationGraphicsFromJSON(json: any): OrganizationGraphics {
    return OrganizationGraphicsFromJSONTyped(json, false);
}

export function OrganizationGraphicsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGraphics {
    if (json == null) {
        return json;
    }
    return {
        
        'throughputByTime': json['throughputByTime'] == null ? undefined : ((json['throughputByTime'] as Array<any>).map(OrganizationGraphicsThroughputByTimeInnerFromJSON)),
        'totalLoadByTime': json['totalLoadByTime'] == null ? undefined : ((json['totalLoadByTime'] as Array<any>).map(OrganizationGraphicsTotalLoadByTimeInnerFromJSON)),
    };
}

export function OrganizationGraphicsToJSON(json: any): OrganizationGraphics {
    return OrganizationGraphicsToJSONTyped(json, false);
}

export function OrganizationGraphicsToJSONTyped(value?: OrganizationGraphics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'throughputByTime': value['throughputByTime'] == null ? undefined : ((value['throughputByTime'] as Array<any>).map(OrganizationGraphicsThroughputByTimeInnerToJSON)),
        'totalLoadByTime': value['totalLoadByTime'] == null ? undefined : ((value['totalLoadByTime'] as Array<any>).map(OrganizationGraphicsTotalLoadByTimeInnerToJSON)),
    };
}

