/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationGraphicsThroughputByTimeInner
 */
export interface OrganizationGraphicsThroughputByTimeInner {
    /**
     * 
     * @type {Date}
     * @memberof OrganizationGraphicsThroughputByTimeInner
     */
    time?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrganizationGraphicsThroughputByTimeInner
     */
    throughput?: number;
}

/**
 * Check if a given object implements the OrganizationGraphicsThroughputByTimeInner interface.
 */
export function instanceOfOrganizationGraphicsThroughputByTimeInner(value: object): value is OrganizationGraphicsThroughputByTimeInner {
    return true;
}

export function OrganizationGraphicsThroughputByTimeInnerFromJSON(json: any): OrganizationGraphicsThroughputByTimeInner {
    return OrganizationGraphicsThroughputByTimeInnerFromJSONTyped(json, false);
}

export function OrganizationGraphicsThroughputByTimeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGraphicsThroughputByTimeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'throughput': json['throughput'] == null ? undefined : json['throughput'],
    };
}

export function OrganizationGraphicsThroughputByTimeInnerToJSON(json: any): OrganizationGraphicsThroughputByTimeInner {
    return OrganizationGraphicsThroughputByTimeInnerToJSONTyped(json, false);
}

export function OrganizationGraphicsThroughputByTimeInnerToJSONTyped(value?: OrganizationGraphicsThroughputByTimeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
        'throughput': value['throughput'],
    };
}

