/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationGraphics } from './OrganizationGraphics';
import {
    OrganizationGraphicsFromJSON,
    OrganizationGraphicsFromJSONTyped,
    OrganizationGraphicsToJSON,
    OrganizationGraphicsToJSONTyped,
} from './OrganizationGraphics';

/**
 * 
 * @export
 * @interface OrganizationGraphicsResponse
 */
export interface OrganizationGraphicsResponse {
    /**
     * 
     * @type {OrganizationGraphics}
     * @memberof OrganizationGraphicsResponse
     */
    graphics?: OrganizationGraphics;
}

/**
 * Check if a given object implements the OrganizationGraphicsResponse interface.
 */
export function instanceOfOrganizationGraphicsResponse(value: object): value is OrganizationGraphicsResponse {
    return true;
}

export function OrganizationGraphicsResponseFromJSON(json: any): OrganizationGraphicsResponse {
    return OrganizationGraphicsResponseFromJSONTyped(json, false);
}

export function OrganizationGraphicsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGraphicsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'graphics': json['graphics'] == null ? undefined : OrganizationGraphicsFromJSON(json['graphics']),
    };
}

export function OrganizationGraphicsResponseToJSON(json: any): OrganizationGraphicsResponse {
    return OrganizationGraphicsResponseToJSONTyped(json, false);
}

export function OrganizationGraphicsResponseToJSONTyped(value?: OrganizationGraphicsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'graphics': OrganizationGraphicsToJSON(value['graphics']),
    };
}

