/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueEntryStatus } from './QueueEntryStatus';
import {
    QueueEntryStatusFromJSON,
    QueueEntryStatusFromJSONTyped,
    QueueEntryStatusToJSON,
    QueueEntryStatusToJSONTyped,
} from './QueueEntryStatus';

/**
 * 
 * @export
 * @interface QueueEntryResponse
 */
export interface QueueEntryResponse {
    /**
     * 
     * @type {string}
     * @memberof QueueEntryResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof QueueEntryResponse
     */
    login?: string;
    /**
     * 
     * @type {number}
     * @memberof QueueEntryResponse
     */
    peopleInFront?: number;
    /**
     * 
     * @type {QueueEntryStatus}
     * @memberof QueueEntryResponse
     */
    status?: QueueEntryStatus;
}



/**
 * Check if a given object implements the QueueEntryResponse interface.
 */
export function instanceOfQueueEntryResponse(value: object): value is QueueEntryResponse {
    return true;
}

export function QueueEntryResponseFromJSON(json: any): QueueEntryResponse {
    return QueueEntryResponseFromJSONTyped(json, false);
}

export function QueueEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'login': json['login'] == null ? undefined : json['login'],
        'peopleInFront': json['peopleInFront'] == null ? undefined : json['peopleInFront'],
        'status': json['status'] == null ? undefined : QueueEntryStatusFromJSON(json['status']),
    };
}

export function QueueEntryResponseToJSON(json: any): QueueEntryResponse {
    return QueueEntryResponseToJSONTyped(json, false);
}

export function QueueEntryResponseToJSONTyped(value?: QueueEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'login': value['login'],
        'peopleInFront': value['peopleInFront'],
        'status': QueueEntryStatusToJSON(value['status']),
    };
}

