/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueSettings
 */
export interface QueueSettings {
    /**
     * 
     * @type {number}
     * @memberof QueueSettings
     */
    arrivalGracePeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueSettings
     */
    maxQueueSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof QueueSettings
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the QueueSettings interface.
 */
export function instanceOfQueueSettings(value: object): value is QueueSettings {
    return true;
}

export function QueueSettingsFromJSON(json: any): QueueSettings {
    return QueueSettingsFromJSONTyped(json, false);
}

export function QueueSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'arrivalGracePeriod': json['arrivalGracePeriod'] == null ? undefined : json['arrivalGracePeriod'],
        'maxQueueSize': json['maxQueueSize'] == null ? undefined : json['maxQueueSize'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function QueueSettingsToJSON(json: any): QueueSettings {
    return QueueSettingsToJSONTyped(json, false);
}

export function QueueSettingsToJSONTyped(value?: QueueSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arrivalGracePeriod': value['arrivalGracePeriod'],
        'maxQueueSize': value['maxQueueSize'],
        'isActive': value['isActive'],
    };
}

