/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueGraphicsAverageWaitingTimeByTimeInner
 */
export interface QueueGraphicsAverageWaitingTimeByTimeInner {
    /**
     * 
     * @type {Date}
     * @memberof QueueGraphicsAverageWaitingTimeByTimeInner
     */
    time?: Date;
    /**
     * 
     * @type {number}
     * @memberof QueueGraphicsAverageWaitingTimeByTimeInner
     */
    waitingTime?: number;
}

/**
 * Check if a given object implements the QueueGraphicsAverageWaitingTimeByTimeInner interface.
 */
export function instanceOfQueueGraphicsAverageWaitingTimeByTimeInner(value: object): value is QueueGraphicsAverageWaitingTimeByTimeInner {
    return true;
}

export function QueueGraphicsAverageWaitingTimeByTimeInnerFromJSON(json: any): QueueGraphicsAverageWaitingTimeByTimeInner {
    return QueueGraphicsAverageWaitingTimeByTimeInnerFromJSONTyped(json, false);
}

export function QueueGraphicsAverageWaitingTimeByTimeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueGraphicsAverageWaitingTimeByTimeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'waitingTime': json['waitingTime'] == null ? undefined : json['waitingTime'],
    };
}

export function QueueGraphicsAverageWaitingTimeByTimeInnerToJSON(json: any): QueueGraphicsAverageWaitingTimeByTimeInner {
    return QueueGraphicsAverageWaitingTimeByTimeInnerToJSONTyped(json, false);
}

export function QueueGraphicsAverageWaitingTimeByTimeInnerToJSONTyped(value?: QueueGraphicsAverageWaitingTimeByTimeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
        'waitingTime': value['waitingTime'],
    };
}

