/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueMetrics
 */
export interface QueueMetrics {
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    waitingTime?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    entriesInTheQueue?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    numberOfServedMembers?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    serviceTime?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    totalLeft?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    maxInQueue?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    minInQueue?: number;
    /**
     * 
     * @type {number}
     * @memberof QueueMetrics
     */
    averageInQueue?: number;
}

/**
 * Check if a given object implements the QueueMetrics interface.
 */
export function instanceOfQueueMetrics(value: object): value is QueueMetrics {
    return true;
}

export function QueueMetricsFromJSON(json: any): QueueMetrics {
    return QueueMetricsFromJSONTyped(json, false);
}

export function QueueMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'waitingTime': json['waitingTime'] == null ? undefined : json['waitingTime'],
        'entriesInTheQueue': json['entriesInTheQueue'] == null ? undefined : json['entriesInTheQueue'],
        'numberOfServedMembers': json['numberOfServedMembers'] == null ? undefined : json['numberOfServedMembers'],
        'serviceTime': json['serviceTime'] == null ? undefined : json['serviceTime'],
        'totalLeft': json['totalLeft'] == null ? undefined : json['totalLeft'],
        'maxInQueue': json['maxInQueue'] == null ? undefined : json['maxInQueue'],
        'minInQueue': json['minInQueue'] == null ? undefined : json['minInQueue'],
        'averageInQueue': json['averageInQueue'] == null ? undefined : json['averageInQueue'],
    };
}

export function QueueMetricsToJSON(json: any): QueueMetrics {
    return QueueMetricsToJSONTyped(json, false);
}

export function QueueMetricsToJSONTyped(value?: QueueMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'waitingTime': value['waitingTime'],
        'entriesInTheQueue': value['entriesInTheQueue'],
        'numberOfServedMembers': value['numberOfServedMembers'],
        'serviceTime': value['serviceTime'],
        'totalLeft': value['totalLeft'],
        'maxInQueue': value['maxInQueue'],
        'minInQueue': value['minInQueue'],
        'averageInQueue': value['averageInQueue'],
    };
}

