/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueGraphicsMembersInQueueByTimeInner
 */
export interface QueueGraphicsMembersInQueueByTimeInner {
    /**
     * 
     * @type {Date}
     * @memberof QueueGraphicsMembersInQueueByTimeInner
     */
    time?: Date;
    /**
     * 
     * @type {number}
     * @memberof QueueGraphicsMembersInQueueByTimeInner
     */
    count?: number;
}

/**
 * Check if a given object implements the QueueGraphicsMembersInQueueByTimeInner interface.
 */
export function instanceOfQueueGraphicsMembersInQueueByTimeInner(value: object): value is QueueGraphicsMembersInQueueByTimeInner {
    return true;
}

export function QueueGraphicsMembersInQueueByTimeInnerFromJSON(json: any): QueueGraphicsMembersInQueueByTimeInner {
    return QueueGraphicsMembersInQueueByTimeInnerFromJSONTyped(json, false);
}

export function QueueGraphicsMembersInQueueByTimeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueGraphicsMembersInQueueByTimeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function QueueGraphicsMembersInQueueByTimeInnerToJSON(json: any): QueueGraphicsMembersInQueueByTimeInner {
    return QueueGraphicsMembersInQueueByTimeInnerToJSONTyped(json, false);
}

export function QueueGraphicsMembersInQueueByTimeInnerToJSONTyped(value?: QueueGraphicsMembersInQueueByTimeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
        'count': value['count'],
    };
}

