/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueGraphicsMembersInQueueByTimeInner } from './QueueGraphicsMembersInQueueByTimeInner';
import {
    QueueGraphicsMembersInQueueByTimeInnerFromJSON,
    QueueGraphicsMembersInQueueByTimeInnerFromJSONTyped,
    QueueGraphicsMembersInQueueByTimeInnerToJSON,
    QueueGraphicsMembersInQueueByTimeInnerToJSONTyped,
} from './QueueGraphicsMembersInQueueByTimeInner';
import type { QueueGraphicsAverageWaitingTimeByTimeInner } from './QueueGraphicsAverageWaitingTimeByTimeInner';
import {
    QueueGraphicsAverageWaitingTimeByTimeInnerFromJSON,
    QueueGraphicsAverageWaitingTimeByTimeInnerFromJSONTyped,
    QueueGraphicsAverageWaitingTimeByTimeInnerToJSON,
    QueueGraphicsAverageWaitingTimeByTimeInnerToJSONTyped,
} from './QueueGraphicsAverageWaitingTimeByTimeInner';

/**
 * 
 * @export
 * @interface QueueGraphics
 */
export interface QueueGraphics {
    /**
     * 
     * @type {Array<QueueGraphicsMembersInQueueByTimeInner>}
     * @memberof QueueGraphics
     */
    membersInQueueByTime?: Array<QueueGraphicsMembersInQueueByTimeInner>;
    /**
     * 
     * @type {Array<QueueGraphicsAverageWaitingTimeByTimeInner>}
     * @memberof QueueGraphics
     */
    averageWaitingTimeByTime?: Array<QueueGraphicsAverageWaitingTimeByTimeInner>;
}

/**
 * Check if a given object implements the QueueGraphics interface.
 */
export function instanceOfQueueGraphics(value: object): value is QueueGraphics {
    return true;
}

export function QueueGraphicsFromJSON(json: any): QueueGraphics {
    return QueueGraphicsFromJSONTyped(json, false);
}

export function QueueGraphicsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueGraphics {
    if (json == null) {
        return json;
    }
    return {
        
        'membersInQueueByTime': json['membersInQueueByTime'] == null ? undefined : ((json['membersInQueueByTime'] as Array<any>).map(QueueGraphicsMembersInQueueByTimeInnerFromJSON)),
        'averageWaitingTimeByTime': json['averageWaitingTimeByTime'] == null ? undefined : ((json['averageWaitingTimeByTime'] as Array<any>).map(QueueGraphicsAverageWaitingTimeByTimeInnerFromJSON)),
    };
}

export function QueueGraphicsToJSON(json: any): QueueGraphics {
    return QueueGraphicsToJSONTyped(json, false);
}

export function QueueGraphicsToJSONTyped(value?: QueueGraphics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'membersInQueueByTime': value['membersInQueueByTime'] == null ? undefined : ((value['membersInQueueByTime'] as Array<any>).map(QueueGraphicsMembersInQueueByTimeInnerToJSON)),
        'averageWaitingTimeByTime': value['averageWaitingTimeByTime'] == null ? undefined : ((value['averageWaitingTimeByTime'] as Array<any>).map(QueueGraphicsAverageWaitingTimeByTimeInnerToJSON)),
    };
}

