/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueMetrics } from './QueueMetrics';
import {
    QueueMetricsFromJSON,
    QueueMetricsFromJSONTyped,
    QueueMetricsToJSON,
    QueueMetricsToJSONTyped,
} from './QueueMetrics';

/**
 * 
 * @export
 * @interface QueueMetricsResponse
 */
export interface QueueMetricsResponse {
    /**
     * 
     * @type {QueueMetrics}
     * @memberof QueueMetricsResponse
     */
    metrics?: QueueMetrics;
}

/**
 * Check if a given object implements the QueueMetricsResponse interface.
 */
export function instanceOfQueueMetricsResponse(value: object): value is QueueMetricsResponse {
    return true;
}

export function QueueMetricsResponseFromJSON(json: any): QueueMetricsResponse {
    return QueueMetricsResponseFromJSONTyped(json, false);
}

export function QueueMetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueMetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metrics': json['metrics'] == null ? undefined : QueueMetricsFromJSON(json['metrics']),
    };
}

export function QueueMetricsResponseToJSON(json: any): QueueMetricsResponse {
    return QueueMetricsResponseToJSONTyped(json, false);
}

export function QueueMetricsResponseToJSONTyped(value?: QueueMetricsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metrics': QueueMetricsToJSON(value['metrics']),
    };
}

