/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of queue entry
 * @export
 */
export const QueueEntryStatus = {
    Waiting: 'WAITING',
    Serving: 'SERVING',
    Served: 'SERVED',
    Canceled: 'CANCELED',
    Missed: 'MISSED'
} as const;
export type QueueEntryStatus = typeof QueueEntryStatus[keyof typeof QueueEntryStatus];


export function instanceOfQueueEntryStatus(value: any): boolean {
    for (const key in QueueEntryStatus) {
        if (Object.prototype.hasOwnProperty.call(QueueEntryStatus, key)) {
            if (QueueEntryStatus[key as keyof typeof QueueEntryStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QueueEntryStatusFromJSON(json: any): QueueEntryStatus {
    return QueueEntryStatusFromJSONTyped(json, false);
}

export function QueueEntryStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueEntryStatus {
    return json as QueueEntryStatus;
}

export function QueueEntryStatusToJSON(value?: QueueEntryStatus | null): any {
    return value as any;
}

export function QueueEntryStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): QueueEntryStatus {
    return value as QueueEntryStatus;
}

