/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueGraphics } from './QueueGraphics';
import {
    QueueGraphicsFromJSON,
    QueueGraphicsFromJSONTyped,
    QueueGraphicsToJSON,
    QueueGraphicsToJSONTyped,
} from './QueueGraphics';

/**
 * 
 * @export
 * @interface QueueGraphicsResponse
 */
export interface QueueGraphicsResponse {
    /**
     * 
     * @type {QueueGraphics}
     * @memberof QueueGraphicsResponse
     */
    graphics?: QueueGraphics;
}

/**
 * Check if a given object implements the QueueGraphicsResponse interface.
 */
export function instanceOfQueueGraphicsResponse(value: object): value is QueueGraphicsResponse {
    return true;
}

export function QueueGraphicsResponseFromJSON(json: any): QueueGraphicsResponse {
    return QueueGraphicsResponseFromJSONTyped(json, false);
}

export function QueueGraphicsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueGraphicsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'graphics': json['graphics'] == null ? undefined : QueueGraphicsFromJSON(json['graphics']),
    };
}

export function QueueGraphicsResponseToJSON(json: any): QueueGraphicsResponse {
    return QueueGraphicsResponseToJSONTyped(json, false);
}

export function QueueGraphicsResponseToJSONTyped(value?: QueueGraphicsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'graphics': QueueGraphicsToJSON(value['graphics']),
    };
}

