/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueEntryCreatingRequest
 */
export interface QueueEntryCreatingRequest {
    /**
     * 
     * @type {number}
     * @memberof QueueEntryCreatingRequest
     */
    maxId: number;
    /**
     * 
     * @type {string}
     * @memberof QueueEntryCreatingRequest
     */
    queueId: string;
}

/**
 * Check if a given object implements the QueueEntryCreatingRequest interface.
 */
export function instanceOfQueueEntryCreatingRequest(value: object): value is QueueEntryCreatingRequest {
    if (!('maxId' in value) || value['maxId'] === undefined) return false;
    if (!('queueId' in value) || value['queueId'] === undefined) return false;
    return true;
}

export function QueueEntryCreatingRequestFromJSON(json: any): QueueEntryCreatingRequest {
    return QueueEntryCreatingRequestFromJSONTyped(json, false);
}

export function QueueEntryCreatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueEntryCreatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'maxId': json['maxId'],
        'queueId': json['queueId'],
    };
}

export function QueueEntryCreatingRequestToJSON(json: any): QueueEntryCreatingRequest {
    return QueueEntryCreatingRequestToJSONTyped(json, false);
}

export function QueueEntryCreatingRequestToJSONTyped(value?: QueueEntryCreatingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxId': value['maxId'],
        'queueId': value['queueId'],
    };
}

