/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueSettings } from './QueueSettings';
import {
    QueueSettingsFromJSON,
    QueueSettingsFromJSONTyped,
    QueueSettingsToJSON,
    QueueSettingsToJSONTyped,
} from './QueueSettings';

/**
 * 
 * @export
 * @interface QueueSettingsResponse
 */
export interface QueueSettingsResponse {
    /**
     * 
     * @type {QueueSettings}
     * @memberof QueueSettingsResponse
     */
    settings?: QueueSettings;
}

/**
 * Check if a given object implements the QueueSettingsResponse interface.
 */
export function instanceOfQueueSettingsResponse(value: object): value is QueueSettingsResponse {
    return true;
}

export function QueueSettingsResponseFromJSON(json: any): QueueSettingsResponse {
    return QueueSettingsResponseFromJSONTyped(json, false);
}

export function QueueSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'settings': json['settings'] == null ? undefined : QueueSettingsFromJSON(json['settings']),
    };
}

export function QueueSettingsResponseToJSON(json: any): QueueSettingsResponse {
    return QueueSettingsResponseToJSONTyped(json, false);
}

export function QueueSettingsResponseToJSONTyped(value?: QueueSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': QueueSettingsToJSON(value['settings']),
    };
}

