/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueMember } from './QueueMember';
import {
    QueueMemberFromJSON,
    QueueMemberFromJSONTyped,
    QueueMemberToJSON,
    QueueMemberToJSONTyped,
} from './QueueMember';

/**
 * 
 * @export
 * @interface QueueMembersResponse
 */
export interface QueueMembersResponse {
    /**
     * 
     * @type {Array<QueueMember>}
     * @memberof QueueMembersResponse
     */
    members?: Array<QueueMember>;
}

/**
 * Check if a given object implements the QueueMembersResponse interface.
 */
export function instanceOfQueueMembersResponse(value: object): value is QueueMembersResponse {
    return true;
}

export function QueueMembersResponseFromJSON(json: any): QueueMembersResponse {
    return QueueMembersResponseFromJSONTyped(json, false);
}

export function QueueMembersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueMembersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(QueueMemberFromJSON)),
    };
}

export function QueueMembersResponseToJSON(json: any): QueueMembersResponse {
    return QueueMembersResponseToJSONTyped(json, false);
}

export function QueueMembersResponseToJSONTyped(value?: QueueMembersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(QueueMemberToJSON)),
    };
}

