/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Queue } from './Queue';
import {
    QueueFromJSON,
    QueueFromJSONTyped,
    QueueToJSON,
    QueueToJSONTyped,
} from './Queue';

/**
 * 
 * @export
 * @interface QueueResponse
 */
export interface QueueResponse {
    /**
     * 
     * @type {Array<Queue>}
     * @memberof QueueResponse
     */
    queues?: Array<Queue>;
}

/**
 * Check if a given object implements the QueueResponse interface.
 */
export function instanceOfQueueResponse(value: object): value is QueueResponse {
    return true;
}

export function QueueResponseFromJSON(json: any): QueueResponse {
    return QueueResponseFromJSONTyped(json, false);
}

export function QueueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'queues': json['queues'] == null ? undefined : ((json['queues'] as Array<any>).map(QueueFromJSON)),
    };
}

export function QueueResponseToJSON(json: any): QueueResponse {
    return QueueResponseToJSONTyped(json, false);
}

export function QueueResponseToJSONTyped(value?: QueueResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queues': value['queues'] == null ? undefined : ((value['queues'] as Array<any>).map(QueueToJSON)),
    };
}

