/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendUserMiniAppDataRequest
 */
export interface SendUserMiniAppDataRequest {
    /**
     * 
     * @type {string}
     * @memberof SendUserMiniAppDataRequest
     */
    miniAppInitData: string;
}

/**
 * Check if a given object implements the SendUserMiniAppDataRequest interface.
 */
export function instanceOfSendUserMiniAppDataRequest(value: object): value is SendUserMiniAppDataRequest {
    if (!('miniAppInitData' in value) || value['miniAppInitData'] === undefined) return false;
    return true;
}

export function SendUserMiniAppDataRequestFromJSON(json: any): SendUserMiniAppDataRequest {
    return SendUserMiniAppDataRequestFromJSONTyped(json, false);
}

export function SendUserMiniAppDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendUserMiniAppDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'miniAppInitData': json['miniAppInitData'],
    };
}

export function SendUserMiniAppDataRequestToJSON(json: any): SendUserMiniAppDataRequest {
    return SendUserMiniAppDataRequestToJSONTyped(json, false);
}

export function SendUserMiniAppDataRequestToJSONTyped(value?: SendUserMiniAppDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'miniAppInitData': value['miniAppInitData'],
    };
}

