/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleOrganization
 */
export interface SimpleOrganization {
    /**
     * 
     * @type {string}
     * @memberof SimpleOrganization
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleOrganization
     */
    name?: string;
}

/**
 * Check if a given object implements the SimpleOrganization interface.
 */
export function instanceOfSimpleOrganization(value: object): value is SimpleOrganization {
    return true;
}

export function SimpleOrganizationFromJSON(json: any): SimpleOrganization {
    return SimpleOrganizationFromJSONTyped(json, false);
}

export function SimpleOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SimpleOrganizationToJSON(json: any): SimpleOrganization {
    return SimpleOrganizationToJSONTyped(json, false);
}

export function SimpleOrganizationToJSONTyped(value?: SimpleOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

