/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleQueue
 */
export interface SimpleQueue {
    /**
     * 
     * @type {string}
     * @memberof SimpleQueue
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleQueue
     */
    name?: string;
}

/**
 * Check if a given object implements the SimpleQueue interface.
 */
export function instanceOfSimpleQueue(value: object): value is SimpleQueue {
    return true;
}

export function SimpleQueueFromJSON(json: any): SimpleQueue {
    return SimpleQueueFromJSONTyped(json, false);
}

export function SimpleQueueFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleQueue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SimpleQueueToJSON(json: any): SimpleQueue {
    return SimpleQueueToJSONTyped(json, false);
}

export function SimpleQueueToJSONTyped(value?: SimpleQueue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

