/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreatingRequest
 */
export interface UserCreatingRequest {
    /**
     * 
     * @type {string}
     * @memberof UserCreatingRequest
     */
    maxId: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreatingRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreatingRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreatingRequest
     */
    secondName?: string;
}

/**
 * Check if a given object implements the UserCreatingRequest interface.
 */
export function instanceOfUserCreatingRequest(value: object): value is UserCreatingRequest {
    if (!('maxId' in value) || value['maxId'] === undefined) return false;
    return true;
}

export function UserCreatingRequestFromJSON(json: any): UserCreatingRequest {
    return UserCreatingRequestFromJSONTyped(json, false);
}

export function UserCreatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'maxId': json['maxId'],
        'username': json['username'] == null ? undefined : json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'secondName': json['secondName'] == null ? undefined : json['secondName'],
    };
}

export function UserCreatingRequestToJSON(json: any): UserCreatingRequest {
    return UserCreatingRequestToJSONTyped(json, false);
}

export function UserCreatingRequestToJSONTyped(value?: UserCreatingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxId': value['maxId'],
        'username': value['username'],
        'firstName': value['firstName'],
        'secondName': value['secondName'],
    };
}

