/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueEntryInUserResponse } from './QueueEntryInUserResponse';
import {
    QueueEntryInUserResponseFromJSON,
    QueueEntryInUserResponseFromJSONTyped,
    QueueEntryInUserResponseToJSON,
    QueueEntryInUserResponseToJSONTyped,
} from './QueueEntryInUserResponse';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof UserResponse
     */
    organizations?: Array<Organization>;
    /**
     * 
     * @type {Array<QueueEntryInUserResponse>}
     * @memberof UserResponse
     */
    queueEntries?: Array<QueueEntryInUserResponse>;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'organizations': json['organizations'] == null ? undefined : ((json['organizations'] as Array<any>).map(OrganizationFromJSON)),
        'queueEntries': json['queue-entries'] == null ? undefined : ((json['queue-entries'] as Array<any>).map(QueueEntryInUserResponseFromJSON)),
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizations': value['organizations'] == null ? undefined : ((value['organizations'] as Array<any>).map(OrganizationToJSON)),
        'queue-entries': value['queueEntries'] == null ? undefined : ((value['queueEntries'] as Array<any>).map(QueueEntryInUserResponseToJSON)),
    };
}

