/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';

/**
 * 
 * @export
 * @interface UserRoleRequest
 */
export interface UserRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof UserRoleRequest
     */
    organizationId: string;
    /**
     * 
     * @type {UserRole}
     * @memberof UserRoleRequest
     */
    role: UserRole;
}



/**
 * Check if a given object implements the UserRoleRequest interface.
 */
export function instanceOfUserRoleRequest(value: object): value is UserRoleRequest {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserRoleRequestFromJSON(json: any): UserRoleRequest {
    return UserRoleRequestFromJSONTyped(json, false);
}

export function UserRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'],
        'role': UserRoleFromJSON(json['role']),
    };
}

export function UserRoleRequestToJSON(json: any): UserRoleRequest {
    return UserRoleRequestToJSONTyped(json, false);
}

export function UserRoleRequestToJSONTyped(value?: UserRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'role': UserRoleToJSON(value['role']),
    };
}

