// Package service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package service

// OrganizationMetrics defines model for OrganizationMetrics.
type OrganizationMetrics struct {
	AverageLoadInQueues        *float32 `json:"averageLoadInQueues,omitempty"`
	MembersInDay               *int     `json:"membersInDay,omitempty"`
	NumberOfActiveQueues       *int     `json:"numberOfActiveQueues,omitempty"`
	NumberOfEmployees          *int     `json:"numberOfEmployees,omitempty"`
	NumberOfMembersInAllQueues *int     `json:"numberOfMembersInAllQueues,omitempty"`
	NumberOfQueues             *int     `json:"numberOfQueues,omitempty"`
	NumberOfServedMembers      *int     `json:"numberOfServedMembers,omitempty"`
	WaitingTime                *float32 `json:"waitingTime,omitempty"`
}

// OrganizationMetricsResponse defines model for OrganizationMetricsResponse.
type OrganizationMetricsResponse struct {
	Metrics *OrganizationMetrics `json:"metrics,omitempty"`
}

// QueueMetrics defines model for QueueMetrics.
type QueueMetrics struct {
	AverageInQueue        *int     `json:"averageInQueue,omitempty"`
	EntriesInTheQueue     *int     `json:"entriesInTheQueue,omitempty"`
	MaxInQueue            *int     `json:"maxInQueue,omitempty"`
	MinInQueue            *int     `json:"minInQueue,omitempty"`
	NumberOfServedMembers *int     `json:"numberOfServedMembers,omitempty"`
	ServiceTime           *float32 `json:"serviceTime,omitempty"`
	TotalLeft             *int     `json:"totalLeft,omitempty"`
	WaitingTime           *float32 `json:"waitingTime,omitempty"`
}

// QueueMetricsResponse defines model for QueueMetricsResponse.
type QueueMetricsResponse struct {
	Metrics *QueueMetrics `json:"metrics,omitempty"`
}
