// Package service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package service

import (
	"time"
)

// OrganizationGraphics defines model for OrganizationGraphics.
type OrganizationGraphics struct {
	ThroughputByTime *[]struct {
		Throughput *int       `json:"throughput,omitempty"`
		Time       *time.Time `json:"time,omitempty"`
	} `json:"throughputByTime,omitempty"`
	TotalLoadByTime *[]struct {
		Time      *time.Time `json:"time,omitempty"`
		TotalLoad *int       `json:"totalLoad,omitempty"`
	} `json:"totalLoadByTime,omitempty"`
}

// OrganizationGraphicsResponse defines model for OrganizationGraphicsResponse.
type OrganizationGraphicsResponse struct {
	Graphics *OrganizationGraphics `json:"graphics,omitempty"`
}

// OrganizationMetrics defines model for OrganizationMetrics.
type OrganizationMetrics struct {
	AverageLoadInQueues        *float32 `json:"averageLoadInQueues,omitempty"`
	MembersInDay               *int     `json:"membersInDay,omitempty"`
	NumberOfActiveQueues       *int     `json:"numberOfActiveQueues,omitempty"`
	NumberOfEmployees          *int     `json:"numberOfEmployees,omitempty"`
	NumberOfMembersInAllQueues *int     `json:"numberOfMembersInAllQueues,omitempty"`
	NumberOfQueues             *int     `json:"numberOfQueues,omitempty"`
	NumberOfServedMembers      *int     `json:"numberOfServedMembers,omitempty"`
	WaitingTime                *float32 `json:"waitingTime,omitempty"`
}

// OrganizationMetricsResponse defines model for OrganizationMetricsResponse.
type OrganizationMetricsResponse struct {
	Metrics *OrganizationMetrics `json:"metrics,omitempty"`
}

// QueueGraphics defines model for QueueGraphics.
type QueueGraphics struct {
	AverageWaitingTimeByTime *[]struct {
		Time        *time.Time `json:"time,omitempty"`
		WaitingTime *float32   `json:"waitingTime,omitempty"`
	} `json:"averageWaitingTimeByTime,omitempty"`
	MembersInQueueByTime *[]struct {
		Count *int       `json:"count,omitempty"`
		Time  *time.Time `json:"time,omitempty"`
	} `json:"membersInQueueByTime,omitempty"`
}

// QueueGraphicsResponse defines model for QueueGraphicsResponse.
type QueueGraphicsResponse struct {
	Graphics *QueueGraphics `json:"graphics,omitempty"`
}

// QueueMetrics defines model for QueueMetrics.
type QueueMetrics struct {
	AverageInQueue        *int     `json:"averageInQueue,omitempty"`
	EntriesInTheQueue     *int     `json:"entriesInTheQueue,omitempty"`
	MaxInQueue            *int     `json:"maxInQueue,omitempty"`
	MinInQueue            *int     `json:"minInQueue,omitempty"`
	NumberOfServedMembers *int     `json:"numberOfServedMembers,omitempty"`
	ServiceTime           *float32 `json:"serviceTime,omitempty"`
	TotalLeft             *int     `json:"totalLeft,omitempty"`
	WaitingTime           *float32 `json:"waitingTime,omitempty"`
}

// QueueMetricsResponse defines model for QueueMetricsResponse.
type QueueMetricsResponse struct {
	Metrics *QueueMetrics `json:"metrics,omitempty"`
}
