openapi: 3.0.4
info:
  title: MaxQueue Metrics API
  version: 0.0.1

paths:
  ### Analitycs service ###
  
  # Metrics
  /organizations/{organizationId}/metrics:
    get:
      tags: [organizations]
      summary: Get organization metrics
      operationId: getOrganizationMetrics
      parameters:
        - name: organizationId
          in: path
          required: true
          description: Organization ID
          schema:
            type: string
      responses:
        '200':
          description: Organization metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationMetricsResponse'
  
  /queues/{queueId}/metrics:
    get:
      tags: [queues]
      summary: Get queue metrics
      operationId: getQueueMetrics
      parameters:
        - name: queueId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Queue metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueMetricsResponse'
  
  # Graphics
  /organizations/{organizationId}/graphics:
    get:
      tags: [organizations]
      summary: Get organization graphics
      operationId: getOrganizationGraphics
      parameters:
        - name: organizationId
          in: path
          required: true
          description: Organization ID
          schema:
            type: string
      responses:
        '200':
          description: Organization graphics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationGraphicsResponse'
  
  /queues/{queueId}/graphics:
    get:
      tags: [queues]
      summary: Get queue graphics
      operationId: getQueueGraphics
      parameters:
        - name: queueId
          in: path
          required: true
          description: Queue ID
          schema:
            type: string
      responses:
        '200':
          description: Queue graphics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueGraphicsResponse'
components:
  schemas:
  # --- Organization metrics ---
    OrganizationMetricsResponse:
      type: object
      properties:
        metrics:
          $ref: '#/components/schemas/OrganizationMetrics'

    OrganizationMetrics:
      type: object
      properties:
        numberOfActiveQueues:
          type: integer
        numberOfQueues:
          type: integer
        numberOfMembersInAllQueues:
          type: integer
        numberOfEmployees:
          type: integer
        membersInDay:
          type: integer
        waitingTime:
          type: number
          format: float
        averageLoadInQueues:
          type: number
          format: float
        numberOfServedMembers:
          type: integer
          
  # --- Queue metrics ---
    QueueMetricsResponse:
      type: object
      properties:
        metrics:
          $ref: '#/components/schemas/QueueMetrics'

    QueueMetrics:
      type: object
      properties:
        waitingTime:
          type: number
          format: float
        entriesInTheQueue:
          type: integer
        numberOfServedMembers:
          type: integer
        serviceTime:
          type: number
          format: float
        totalLeft:
          type: integer
        maxInQueue:
          type: integer
        minInQueue:
          type: integer
        averageInQueue:
          type: integer
          
  # --- Queue graphics ---
    QueueGraphicsResponse:
      type: object
      properties:
        graphics:
          $ref: '#/components/schemas/QueueGraphics'

    QueueGraphics:
      type: object
      properties:
        membersInQueueByTime:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
                format: date-time
              count:
                type: integer
        averageWaitingTimeByTime:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
                format: date-time
              waitingTime:
                type: number
                format: float
    
  # --- Organization graphics ---
    OrganizationGraphicsResponse:
      type: object
      properties:
        graphics:
          $ref: '#/components/schemas/OrganizationGraphics'

    OrganizationGraphics:
      type: object
      properties:
        throughputByTime:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
                format: date-time
              throughput:
                type: integer
        totalLoadByTime:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
                format: date-time
              totalLoad:
                type: integer
