/* tslint:disable */
/* eslint-disable */
/**
 * MaxQueue Orchestrator API
 * API, which is the entry point to the MaxQueue project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Organization {
    'id'?: string;
    'name'?: string;
    'role'?: UserRole & string;
    'amountOfQueues'?: number;
}
export interface OrganizationMetrics {
    'numberOfActiveQueues'?: number;
    'numberOfQueues'?: number;
    'numberOfMembersInAllQueues'?: number;
    'numberOfEmployees'?: number;
    'membersInDay'?: number;
    'waitingTime'?: number;
    'averageLoadInQueues'?: number;
    'numberOfServedMembers'?: number;
}
export interface OrganizationMetricsResponse {
    'metrics'?: OrganizationMetrics;
}
export interface OrganizationQueuesResponse {
    'queues'?: Array<SimpleQueue>;
}
export interface OrganizationSettings {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'address'?: string;
    'isBanned'?: boolean;
    'createdAt'?: string;
}
export interface OrganizationSettingsResponse {
    'organization'?: OrganizationSettings;
}
export interface Queue {
    'id'?: string;
    'name'?: string;
}
export interface QueueEntryCreatingRequest {
    'maxId': number;
    'queueId': string;
}

export interface QueueEntryInUserResponse {
    'id'?: string;
    'name'?: string;
    'peopleInFront'?: number;
    'status'?: QueueEntryStatus;
}

export interface QueueEntryResponse {
    'name'?: string;
    'login'?: string;
    'peopleInFront'?: number;
    'status'?: QueueEntryStatus;
}


/**
 * Status of queue entry
 */

export const QueueEntryStatus = {
    Waiting: 'WAITING',
    Serving: 'SERVING',
    Served: 'SERVED',
    Cancelled: 'CANCELLED',
    Missed: 'MISSED'
} as const;

export type QueueEntryStatus = typeof QueueEntryStatus[keyof typeof QueueEntryStatus];


export interface QueueMember {
    'maxId'?: string;
    'queueEntryId'?: string;
    'username'?: string;
}
export interface QueueMembersResponse {
    'members'?: Array<QueueMember>;
}
export interface QueueMetrics {
    'waitingTime'?: number;
    'membersInFragment'?: number;
    'entriesInTheQueue'?: number;
    'numberOfServedMembers'?: number;
    'serviceTime'?: number;
    'totalLeft'?: number;
    'maxInQueue'?: number;
    'minInQueue'?: number;
    'averageInQueue'?: number;
}
export interface QueueMetricsResponse {
    'metrics'?: QueueMetrics;
}
export interface QueueResponse {
    'queues'?: Array<Queue>;
}
export interface QueueSettings {
    'arrivalGracePeriod'?: number;
    'maxQueueSize'?: number;
    'isActive'?: boolean;
}
export interface QueueSettingsResponse {
    'settings'?: QueueSettings;
}
export interface SimpleOrganization {
    'id'?: string;
    'name'?: string;
}
export interface SimpleQueue {
    'id'?: string;
    'name'?: string;
}
export interface UserCreatingRequest {
    'maxId': string;
    'username'?: string;
    'firstName'?: string;
    'secondName'?: string;
}
export interface UserResponse {
    'organizations'?: Array<Organization>;
    'queue-entries'?: Array<QueueEntryInUserResponse>;
}
/**
 * Role of user
 */

export const UserRole = {
    Client: 'CLIENT',
    Employee: 'EMPLOYEE',
    Moderator: 'MODERATOR',
    Admin: 'ADMIN'
} as const;

export type UserRole = typeof UserRole[keyof typeof UserRole];


export interface UserRoleRequest {
    'organizationId': string;
    'role': UserRole;
}


export interface UserUpdateRequest {
    'username'?: string;
    'firstName'?: string;
    'secondName'?: string;
    'createdAt'?: string;
}

/**
 * OrganizationsApi - axios parameter creator
 */
export const OrganizationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get organization metrics
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationMetrics: async (organizationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('getOrganizationMetrics', 'organizationId', organizationId)
            const localVarPath = `/organizations/{organizationId}/metrics`
                .replace(`{${"organizationId"}}`, encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get list of queues in an organization
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationQueues: async (organizationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('getOrganizationQueues', 'organizationId', organizationId)
            const localVarPath = `/organizations/{organizationId}/queues`
                .replace(`{${"organizationId"}}`, encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get organization settings
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationSettings: async (organizationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('getOrganizationSettings', 'organizationId', organizationId)
            const localVarPath = `/organizations/{organizationId}/settings`
                .replace(`{${"organizationId"}}`, encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrganizationsApi - functional programming interface
 */
export const OrganizationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrganizationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get organization metrics
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationMetrics(organizationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationMetricsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationMetrics(organizationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.getOrganizationMetrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get list of queues in an organization
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationQueues(organizationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueueResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationQueues(organizationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.getOrganizationQueues']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get organization settings
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationSettings(organizationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationSettingsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationSettings(organizationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.getOrganizationSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrganizationsApi - factory interface
 */
export const OrganizationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrganizationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get organization metrics
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationMetrics(organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationMetricsResponse> {
            return localVarFp.getOrganizationMetrics(organizationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get list of queues in an organization
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationQueues(organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<QueueResponse> {
            return localVarFp.getOrganizationQueues(organizationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get organization settings
         * @param {string} organizationId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationSettings(organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationSettingsResponse> {
            return localVarFp.getOrganizationSettings(organizationId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrganizationsApi - object-oriented interface
 */
export class OrganizationsApi extends BaseAPI {
    /**
     * 
     * @summary Get organization metrics
     * @param {string} organizationId Organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrganizationMetrics(organizationId: string, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).getOrganizationMetrics(organizationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get list of queues in an organization
     * @param {string} organizationId Organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrganizationQueues(organizationId: string, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).getOrganizationQueues(organizationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get organization settings
     * @param {string} organizationId Organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrganizationSettings(organizationId: string, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).getOrganizationSettings(organizationId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QueueEntriesApi - axios parameter creator
 */
export const QueueEntriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add user in queue
         * @param {QueueEntryCreatingRequest} [queueEntryCreatingRequest] Add user in queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQueueEntry: async (queueEntryCreatingRequest?: QueueEntryCreatingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/queue-entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(queueEntryCreatingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete user from queue
         * @param {string} entryId Queue Entry id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQueueEntry: async (entryId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entryId' is not null or undefined
            assertParamExists('deleteQueueEntry', 'entryId', entryId)
            const localVarPath = `/queue-entries/{entryId}`
                .replace(`{${"entryId"}}`, encodeURIComponent(String(entryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get queue entry
         * @param {string} entryId Queue Entry id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueEntry: async (entryId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entryId' is not null or undefined
            assertParamExists('getQueueEntry', 'entryId', entryId)
            const localVarPath = `/queue-entries/{entryId}`
                .replace(`{${"entryId"}}`, encodeURIComponent(String(entryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QueueEntriesApi - functional programming interface
 */
export const QueueEntriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QueueEntriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add user in queue
         * @param {QueueEntryCreatingRequest} [queueEntryCreatingRequest] Add user in queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addQueueEntry(queueEntryCreatingRequest?: QueueEntryCreatingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addQueueEntry(queueEntryCreatingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueueEntriesApi.addQueueEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete user from queue
         * @param {string} entryId Queue Entry id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteQueueEntry(entryId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteQueueEntry(entryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueueEntriesApi.deleteQueueEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get queue entry
         * @param {string} entryId Queue Entry id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQueueEntry(entryId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueueEntryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQueueEntry(entryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueueEntriesApi.getQueueEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QueueEntriesApi - factory interface
 */
export const QueueEntriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QueueEntriesApiFp(configuration)
    return {
        /**
         * 
         * @summary Add user in queue
         * @param {QueueEntryCreatingRequest} [queueEntryCreatingRequest] Add user in queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQueueEntry(queueEntryCreatingRequest?: QueueEntryCreatingRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addQueueEntry(queueEntryCreatingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete user from queue
         * @param {string} entryId Queue Entry id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQueueEntry(entryId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteQueueEntry(entryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get queue entry
         * @param {string} entryId Queue Entry id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueEntry(entryId: string, options?: RawAxiosRequestConfig): AxiosPromise<QueueEntryResponse> {
            return localVarFp.getQueueEntry(entryId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QueueEntriesApi - object-oriented interface
 */
export class QueueEntriesApi extends BaseAPI {
    /**
     * 
     * @summary Add user in queue
     * @param {QueueEntryCreatingRequest} [queueEntryCreatingRequest] Add user in queue
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addQueueEntry(queueEntryCreatingRequest?: QueueEntryCreatingRequest, options?: RawAxiosRequestConfig) {
        return QueueEntriesApiFp(this.configuration).addQueueEntry(queueEntryCreatingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete user from queue
     * @param {string} entryId Queue Entry id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteQueueEntry(entryId: string, options?: RawAxiosRequestConfig) {
        return QueueEntriesApiFp(this.configuration).deleteQueueEntry(entryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get queue entry
     * @param {string} entryId Queue Entry id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQueueEntry(entryId: string, options?: RawAxiosRequestConfig) {
        return QueueEntriesApiFp(this.configuration).getQueueEntry(entryId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QueuesApi - axios parameter creator
 */
export const QueuesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get members of a queue
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueMembers: async (queueId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queueId' is not null or undefined
            assertParamExists('getQueueMembers', 'queueId', queueId)
            const localVarPath = `/queues/{queueId}/members`
                .replace(`{${"queueId"}}`, encodeURIComponent(String(queueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get queue metrics
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueMetrics: async (queueId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queueId' is not null or undefined
            assertParamExists('getQueueMetrics', 'queueId', queueId)
            const localVarPath = `/queues/{queueId}/metrics`
                .replace(`{${"queueId"}}`, encodeURIComponent(String(queueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get queue settings
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueSettings: async (queueId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queueId' is not null or undefined
            assertParamExists('getQueueSettings', 'queueId', queueId)
            const localVarPath = `/queues/{queueId}/settings`
                .replace(`{${"queueId"}}`, encodeURIComponent(String(queueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QueuesApi - functional programming interface
 */
export const QueuesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QueuesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get members of a queue
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQueueMembers(queueId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueueMembersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQueueMembers(queueId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueuesApi.getQueueMembers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get queue metrics
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQueueMetrics(queueId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueueMetricsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQueueMetrics(queueId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueuesApi.getQueueMetrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get queue settings
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQueueSettings(queueId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueueSettingsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQueueSettings(queueId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueuesApi.getQueueSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QueuesApi - factory interface
 */
export const QueuesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QueuesApiFp(configuration)
    return {
        /**
         * 
         * @summary Get members of a queue
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueMembers(queueId: string, options?: RawAxiosRequestConfig): AxiosPromise<QueueMembersResponse> {
            return localVarFp.getQueueMembers(queueId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get queue metrics
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueMetrics(queueId: string, options?: RawAxiosRequestConfig): AxiosPromise<QueueMetricsResponse> {
            return localVarFp.getQueueMetrics(queueId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get queue settings
         * @param {string} queueId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueueSettings(queueId: string, options?: RawAxiosRequestConfig): AxiosPromise<QueueSettingsResponse> {
            return localVarFp.getQueueSettings(queueId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QueuesApi - object-oriented interface
 */
export class QueuesApi extends BaseAPI {
    /**
     * 
     * @summary Get members of a queue
     * @param {string} queueId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQueueMembers(queueId: string, options?: RawAxiosRequestConfig) {
        return QueuesApiFp(this.configuration).getQueueMembers(queueId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get queue metrics
     * @param {string} queueId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQueueMetrics(queueId: string, options?: RawAxiosRequestConfig) {
        return QueuesApiFp(this.configuration).getQueueMetrics(queueId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get queue settings
     * @param {string} queueId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQueueSettings(queueId: string, options?: RawAxiosRequestConfig) {
        return QueuesApiFp(this.configuration).getQueueSettings(queueId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add user in maxqueue system
         * @param {UserCreatingRequest} [userCreatingRequest] Add user in maxqueue system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addUserInMaxQueueSystem: async (userCreatingRequest?: UserCreatingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreatingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user by Max Messenger ID
         * @param {number} maxId Max Messenger user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByMaxId: async (maxId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'maxId' is not null or undefined
            assertParamExists('getUserByMaxId', 'maxId', maxId)
            const localVarPath = `/users/{maxId}`
                .replace(`{${"maxId"}}`, encodeURIComponent(String(maxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user role in organization
         * @param {number} maxId User MAX ID
         * @param {UserRoleRequest} [userRoleRequest] Update user role in organization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOrganizationUserRole: async (maxId: number, userRoleRequest?: UserRoleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'maxId' is not null or undefined
            assertParamExists('updateOrganizationUserRole', 'maxId', maxId)
            const localVarPath = `/users/{maxId}/role`
                .replace(`{${"maxId"}}`, encodeURIComponent(String(maxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userRoleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user in maxqueue system
         * @param {number} maxId Max Messenger user ID
         * @param {UserUpdateRequest} [userUpdateRequest] Update user in maxqueue system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserInMaxQueueSystem: async (maxId: number, userUpdateRequest?: UserUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'maxId' is not null or undefined
            assertParamExists('updateUserInMaxQueueSystem', 'maxId', maxId)
            const localVarPath = `/users/{maxId}`
                .replace(`{${"maxId"}}`, encodeURIComponent(String(maxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add user in maxqueue system
         * @param {UserCreatingRequest} [userCreatingRequest] Add user in maxqueue system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addUserInMaxQueueSystem(userCreatingRequest?: UserCreatingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addUserInMaxQueueSystem(userCreatingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.addUserInMaxQueueSystem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user by Max Messenger ID
         * @param {number} maxId Max Messenger user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserByMaxId(maxId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserByMaxId(maxId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserByMaxId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update user role in organization
         * @param {number} maxId User MAX ID
         * @param {UserRoleRequest} [userRoleRequest] Update user role in organization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOrganizationUserRole(maxId: number, userRoleRequest?: UserRoleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationQueuesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOrganizationUserRole(maxId, userRoleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateOrganizationUserRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update user in maxqueue system
         * @param {number} maxId Max Messenger user ID
         * @param {UserUpdateRequest} [userUpdateRequest] Update user in maxqueue system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserInMaxQueueSystem(maxId: number, userUpdateRequest?: UserUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserInMaxQueueSystem(maxId, userUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateUserInMaxQueueSystem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary Add user in maxqueue system
         * @param {UserCreatingRequest} [userCreatingRequest] Add user in maxqueue system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addUserInMaxQueueSystem(userCreatingRequest?: UserCreatingRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addUserInMaxQueueSystem(userCreatingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user by Max Messenger ID
         * @param {number} maxId Max Messenger user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByMaxId(maxId: number, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.getUserByMaxId(maxId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user role in organization
         * @param {number} maxId User MAX ID
         * @param {UserRoleRequest} [userRoleRequest] Update user role in organization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOrganizationUserRole(maxId: number, userRoleRequest?: UserRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationQueuesResponse> {
            return localVarFp.updateOrganizationUserRole(maxId, userRoleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user in maxqueue system
         * @param {number} maxId Max Messenger user ID
         * @param {UserUpdateRequest} [userUpdateRequest] Update user in maxqueue system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserInMaxQueueSystem(maxId: number, userUpdateRequest?: UserUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateUserInMaxQueueSystem(maxId, userUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Add user in maxqueue system
     * @param {UserCreatingRequest} [userCreatingRequest] Add user in maxqueue system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addUserInMaxQueueSystem(userCreatingRequest?: UserCreatingRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).addUserInMaxQueueSystem(userCreatingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user by Max Messenger ID
     * @param {number} maxId Max Messenger user ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserByMaxId(maxId: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserByMaxId(maxId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update user role in organization
     * @param {number} maxId User MAX ID
     * @param {UserRoleRequest} [userRoleRequest] Update user role in organization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateOrganizationUserRole(maxId: number, userRoleRequest?: UserRoleRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateOrganizationUserRole(maxId, userRoleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update user in maxqueue system
     * @param {number} maxId Max Messenger user ID
     * @param {UserUpdateRequest} [userUpdateRequest] Update user in maxqueue system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUserInMaxQueueSystem(maxId: number, userUpdateRequest?: UserUpdateRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateUserInMaxQueueSystem(maxId, userUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



